// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: proto/sandbox.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecuteRequest 包含执行代码所需的信息
type ExecuteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Language       string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	SourceCode     string                 `protobuf:"bytes,2,opt,name=source_code,json=sourceCode,proto3" json:"source_code,omitempty"`
	Stdin          string                 `protobuf:"bytes,3,opt,name=stdin,proto3" json:"stdin,omitempty"`
	Timeout        int32                  `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`                                    // 超时时间（秒）
	MemoryLimit    int32                  `protobuf:"varint,5,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`         // 内存限制（MB）
	ExpectedOutput string                 `protobuf:"bytes,6,opt,name=expected_output,json=expectedOutput,proto3" json:"expected_output,omitempty"` // 预期输出，用于比较
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_proto_sandbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sandbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_proto_sandbox_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ExecuteRequest) GetSourceCode() string {
	if x != nil {
		return x.SourceCode
	}
	return ""
}

func (x *ExecuteRequest) GetStdin() string {
	if x != nil {
		return x.Stdin
	}
	return ""
}

func (x *ExecuteRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *ExecuteRequest) GetMemoryLimit() int32 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

func (x *ExecuteRequest) GetExpectedOutput() string {
	if x != nil {
		return x.ExpectedOutput
	}
	return ""
}

// ExecuteResponse 包含代码执行的结果
type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                 // 执行状态 (e.g., Accepted, WrongAnswer, TimeLimitExceeded)
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`            // 进程退出码
	Stdout        string                 `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`                                 // 标准输出
	Stderr        string                 `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`                                 // 标准错误
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`                                   // 内部错误信息
	CompileError  string                 `protobuf:"bytes,6,opt,name=compile_error,json=compileError,proto3" json:"compile_error,omitempty"` // 编译错误信息
	TimeUsed      int64                  `protobuf:"varint,7,opt,name=time_used,json=timeUsed,proto3" json:"time_used,omitempty"`            // 执行时间（毫秒）
	MemoryUsed    int64                  `protobuf:"varint,8,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`      // 内存使用（KB）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_proto_sandbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sandbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_proto_sandbox_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecuteResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecuteResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecuteResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteResponse) GetCompileError() string {
	if x != nil {
		return x.CompileError
	}
	return ""
}

func (x *ExecuteResponse) GetTimeUsed() int64 {
	if x != nil {
		return x.TimeUsed
	}
	return 0
}

func (x *ExecuteResponse) GetMemoryUsed() int64 {
	if x != nil {
		return x.MemoryUsed
	}
	return 0
}

var File_proto_sandbox_proto protoreflect.FileDescriptor

const file_proto_sandbox_proto_rawDesc = "" +
	"\n" +
	"\x13proto/sandbox.proto\x12\asandbox\"\xc9\x01\n" +
	"\x0eExecuteRequest\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x1f\n" +
	"\vsource_code\x18\x02 \x01(\tR\n" +
	"sourceCode\x12\x14\n" +
	"\x05stdin\x18\x03 \x01(\tR\x05stdin\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\x05R\atimeout\x12!\n" +
	"\fmemory_limit\x18\x05 \x01(\x05R\vmemoryLimit\x12'\n" +
	"\x0fexpected_output\x18\x06 \x01(\tR\x0eexpectedOutput\"\xef\x01\n" +
	"\x0fExecuteResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\tR\x06stderr\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12#\n" +
	"\rcompile_error\x18\x06 \x01(\tR\fcompileError\x12\x1b\n" +
	"\ttime_used\x18\a \x01(\x03R\btimeUsed\x12\x1f\n" +
	"\vmemory_used\x18\b \x01(\x03R\n" +
	"memoryUsed2P\n" +
	"\x0eSandboxService\x12>\n" +
	"\aExecute\x12\x17.sandbox.ExecuteRequest\x1a\x18.sandbox.ExecuteResponse\"\x00B*Z(github.com/CodeRushOJ/croj-sandbox/protob\x06proto3"

var (
	file_proto_sandbox_proto_rawDescOnce sync.Once
	file_proto_sandbox_proto_rawDescData []byte
)

func file_proto_sandbox_proto_rawDescGZIP() []byte {
	file_proto_sandbox_proto_rawDescOnce.Do(func() {
		file_proto_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sandbox_proto_rawDesc), len(file_proto_sandbox_proto_rawDesc)))
	})
	return file_proto_sandbox_proto_rawDescData
}

var file_proto_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_sandbox_proto_goTypes = []any{
	(*ExecuteRequest)(nil),  // 0: sandbox.ExecuteRequest
	(*ExecuteResponse)(nil), // 1: sandbox.ExecuteResponse
}
var file_proto_sandbox_proto_depIdxs = []int32{
	0, // 0: sandbox.SandboxService.Execute:input_type -> sandbox.ExecuteRequest
	1, // 1: sandbox.SandboxService.Execute:output_type -> sandbox.ExecuteResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sandbox_proto_init() }
func file_proto_sandbox_proto_init() {
	if File_proto_sandbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sandbox_proto_rawDesc), len(file_proto_sandbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sandbox_proto_goTypes,
		DependencyIndexes: file_proto_sandbox_proto_depIdxs,
		MessageInfos:      file_proto_sandbox_proto_msgTypes,
	}.Build()
	File_proto_sandbox_proto = out.File
	file_proto_sandbox_proto_goTypes = nil
	file_proto_sandbox_proto_depIdxs = nil
}
