// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/sandbox.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteBatchV1Event_Kind int32

const (
	ExecuteBatchV1Event_KIND_UNSPECIFIED ExecuteBatchV1Event_Kind = 0
	ExecuteBatchV1Event_CASE_RESULT      ExecuteBatchV1Event_Kind = 1
	ExecuteBatchV1Event_COMPILE_ERROR    ExecuteBatchV1Event_Kind = 2
	ExecuteBatchV1Event_COMPLETED        ExecuteBatchV1Event_Kind = 3
)

// Enum value maps for ExecuteBatchV1Event_Kind.
var (
	ExecuteBatchV1Event_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "CASE_RESULT",
		2: "COMPILE_ERROR",
		3: "COMPLETED",
	}
	ExecuteBatchV1Event_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"CASE_RESULT":      1,
		"COMPILE_ERROR":    2,
		"COMPLETED":        3,
	}
)

func (x ExecuteBatchV1Event_Kind) Enum() *ExecuteBatchV1Event_Kind {
	p := new(ExecuteBatchV1Event_Kind)
	*p = x
	return p
}

func (x ExecuteBatchV1Event_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecuteBatchV1Event_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_sandbox_proto_enumTypes[0].Descriptor()
}

func (ExecuteBatchV1Event_Kind) Type() protoreflect.EnumType {
	return &file_proto_sandbox_proto_enumTypes[0]
}

func (x ExecuteBatchV1Event_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecuteBatchV1Event_Kind.Descriptor instead.
func (ExecuteBatchV1Event_Kind) EnumDescriptor() ([]byte, []int) {
	return file_proto_sandbox_proto_rawDescGZIP(), []int{4, 0}
}

// ExecuteRequest 包含执行代码所需的信息
type ExecuteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Language       string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	SourceCode     string                 `protobuf:"bytes,2,opt,name=source_code,json=sourceCode,proto3" json:"source_code,omitempty"`
	Stdin          string                 `protobuf:"bytes,3,opt,name=stdin,proto3" json:"stdin,omitempty"`
	Timeout        int32                  `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`                                    // 超时时间（秒）
	MemoryLimit    int32                  `protobuf:"varint,5,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`         // 内存限制（MB）
	ExpectedOutput string                 `protobuf:"bytes,6,opt,name=expected_output,json=expectedOutput,proto3" json:"expected_output,omitempty"` // 预期输出，用于比较
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_proto_sandbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sandbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_proto_sandbox_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ExecuteRequest) GetSourceCode() string {
	if x != nil {
		return x.SourceCode
	}
	return ""
}

func (x *ExecuteRequest) GetStdin() string {
	if x != nil {
		return x.Stdin
	}
	return ""
}

func (x *ExecuteRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *ExecuteRequest) GetMemoryLimit() int32 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

func (x *ExecuteRequest) GetExpectedOutput() string {
	if x != nil {
		return x.ExpectedOutput
	}
	return ""
}

// ExecuteResponse 包含代码执行的结果
type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                 // 执行状态 (e.g., Accepted, WrongAnswer, TimeLimitExceeded)
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`            // 进程退出码
	Stdout        string                 `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`                                 // 标准输出
	Stderr        string                 `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`                                 // 标准错误
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`                                   // 内部错误信息
	CompileError  string                 `protobuf:"bytes,6,opt,name=compile_error,json=compileError,proto3" json:"compile_error,omitempty"` // 编译错误信息
	TimeUsed      int64                  `protobuf:"varint,7,opt,name=time_used,json=timeUsed,proto3" json:"time_used,omitempty"`            // 执行时间（毫秒）
	MemoryUsed    int64                  `protobuf:"varint,8,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`      // 内存使用（KB）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_proto_sandbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sandbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_proto_sandbox_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecuteResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecuteResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecuteResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteResponse) GetCompileError() string {
	if x != nil {
		return x.CompileError
	}
	return ""
}

func (x *ExecuteResponse) GetTimeUsed() int64 {
	if x != nil {
		return x.TimeUsed
	}
	return 0
}

func (x *ExecuteResponse) GetMemoryUsed() int64 {
	if x != nil {
		return x.MemoryUsed
	}
	return 0
}

type ExecuteBatchV1Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	SourceCode    string                 `protobuf:"bytes,2,opt,name=source_code,json=sourceCode,proto3" json:"source_code,omitempty"`
	Timeout       int32                  `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	MemoryLimit   int32                  `protobuf:"varint,4,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	StopOnFailure bool                   `protobuf:"varint,5,opt,name=stop_on_failure,json=stopOnFailure,proto3" json:"stop_on_failure,omitempty"`
	Cases         []*ExecuteBatchV1Case  `protobuf:"bytes,6,rep,name=cases,proto3" json:"cases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteBatchV1Request) Reset() {
	*x = ExecuteBatchV1Request{}
	mi := &file_proto_sandbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteBatchV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteBatchV1Request) ProtoMessage() {}

func (x *ExecuteBatchV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sandbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteBatchV1Request.ProtoReflect.Descriptor instead.
func (*ExecuteBatchV1Request) Descriptor() ([]byte, []int) {
	return file_proto_sandbox_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteBatchV1Request) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ExecuteBatchV1Request) GetSourceCode() string {
	if x != nil {
		return x.SourceCode
	}
	return ""
}

func (x *ExecuteBatchV1Request) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *ExecuteBatchV1Request) GetMemoryLimit() int32 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

func (x *ExecuteBatchV1Request) GetStopOnFailure() bool {
	if x != nil {
		return x.StopOnFailure
	}
	return false
}

func (x *ExecuteBatchV1Request) GetCases() []*ExecuteBatchV1Case {
	if x != nil {
		return x.Cases
	}
	return nil
}

type ExecuteBatchV1Case struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CaseId              string                 `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	Stdin               string                 `protobuf:"bytes,2,opt,name=stdin,proto3" json:"stdin,omitempty"`
	ExpectedOutput      string                 `protobuf:"bytes,3,opt,name=expected_output,json=expectedOutput,proto3" json:"expected_output,omitempty"`
	CompareOutput       bool                   `protobuf:"varint,4,opt,name=compare_output,json=compareOutput,proto3" json:"compare_output,omitempty"`
	TokenExpectedSha256 string                 `protobuf:"bytes,5,opt,name=token_expected_sha256,json=tokenExpectedSha256,proto3" json:"token_expected_sha256,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ExecuteBatchV1Case) Reset() {
	*x = ExecuteBatchV1Case{}
	mi := &file_proto_sandbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteBatchV1Case) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteBatchV1Case) ProtoMessage() {}

func (x *ExecuteBatchV1Case) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sandbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteBatchV1Case.ProtoReflect.Descriptor instead.
func (*ExecuteBatchV1Case) Descriptor() ([]byte, []int) {
	return file_proto_sandbox_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteBatchV1Case) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *ExecuteBatchV1Case) GetStdin() string {
	if x != nil {
		return x.Stdin
	}
	return ""
}

func (x *ExecuteBatchV1Case) GetExpectedOutput() string {
	if x != nil {
		return x.ExpectedOutput
	}
	return ""
}

func (x *ExecuteBatchV1Case) GetCompareOutput() bool {
	if x != nil {
		return x.CompareOutput
	}
	return false
}

func (x *ExecuteBatchV1Case) GetTokenExpectedSha256() string {
	if x != nil {
		return x.TokenExpectedSha256
	}
	return ""
}

type ExecuteBatchV1Event struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Kind          ExecuteBatchV1Event_Kind `protobuf:"varint,1,opt,name=kind,proto3,enum=sandbox.ExecuteBatchV1Event_Kind" json:"kind,omitempty"`
	CaseId        string                   `protobuf:"bytes,2,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	Result        *ExecuteResponse         `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteBatchV1Event) Reset() {
	*x = ExecuteBatchV1Event{}
	mi := &file_proto_sandbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteBatchV1Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteBatchV1Event) ProtoMessage() {}

func (x *ExecuteBatchV1Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sandbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteBatchV1Event.ProtoReflect.Descriptor instead.
func (*ExecuteBatchV1Event) Descriptor() ([]byte, []int) {
	return file_proto_sandbox_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteBatchV1Event) GetKind() ExecuteBatchV1Event_Kind {
	if x != nil {
		return x.Kind
	}
	return ExecuteBatchV1Event_KIND_UNSPECIFIED
}

func (x *ExecuteBatchV1Event) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *ExecuteBatchV1Event) GetResult() *ExecuteResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_proto_sandbox_proto protoreflect.FileDescriptor

const file_proto_sandbox_proto_rawDesc = "" +
	"\n" +
	"\x13proto/sandbox.proto\x12\asandbox\"\xc9\x01\n" +
	"\x0eExecuteRequest\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x1f\n" +
	"\vsource_code\x18\x02 \x01(\tR\n" +
	"sourceCode\x12\x14\n" +
	"\x05stdin\x18\x03 \x01(\tR\x05stdin\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\x05R\atimeout\x12!\n" +
	"\fmemory_limit\x18\x05 \x01(\x05R\vmemoryLimit\x12'\n" +
	"\x0fexpected_output\x18\x06 \x01(\tR\x0eexpectedOutput\"\xef\x01\n" +
	"\x0fExecuteResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\tR\x06stderr\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12#\n" +
	"\rcompile_error\x18\x06 \x01(\tR\fcompileError\x12\x1b\n" +
	"\ttime_used\x18\a \x01(\x03R\btimeUsed\x12\x1f\n" +
	"\vmemory_used\x18\b \x01(\x03R\n" +
	"memoryUsed\"\xec\x01\n" +
	"\x15ExecuteBatchV1Request\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x1f\n" +
	"\vsource_code\x18\x02 \x01(\tR\n" +
	"sourceCode\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x05R\atimeout\x12!\n" +
	"\fmemory_limit\x18\x04 \x01(\x05R\vmemoryLimit\x12&\n" +
	"\x0fstop_on_failure\x18\x05 \x01(\bR\rstopOnFailure\x121\n" +
	"\x05cases\x18\x06 \x03(\v2\x1b.sandbox.ExecuteBatchV1CaseR\x05cases\"\xc7\x01\n" +
	"\x12ExecuteBatchV1Case\x12\x17\n" +
	"\acase_id\x18\x01 \x01(\tR\x06caseId\x12\x14\n" +
	"\x05stdin\x18\x02 \x01(\tR\x05stdin\x12'\n" +
	"\x0fexpected_output\x18\x03 \x01(\tR\x0eexpectedOutput\x12%\n" +
	"\x0ecompare_output\x18\x04 \x01(\bR\rcompareOutput\x122\n" +
	"\x15token_expected_sha256\x18\x05 \x01(\tR\x13tokenExpectedSha256\"\xe8\x01\n" +
	"\x13ExecuteBatchV1Event\x125\n" +
	"\x04kind\x18\x01 \x01(\x0e2!.sandbox.ExecuteBatchV1Event.KindR\x04kind\x12\x17\n" +
	"\acase_id\x18\x02 \x01(\tR\x06caseId\x120\n" +
	"\x06result\x18\x03 \x01(\v2\x18.sandbox.ExecuteResponseR\x06result\"O\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vCASE_RESULT\x10\x01\x12\x11\n" +
	"\rCOMPILE_ERROR\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x032\xa4\x01\n" +
	"\x0eSandboxService\x12>\n" +
	"\aExecute\x12\x17.sandbox.ExecuteRequest\x1a\x18.sandbox.ExecuteResponse\"\x00\x12R\n" +
	"\x0eExecuteBatchV1\x12\x1e.sandbox.ExecuteBatchV1Request\x1a\x1c.sandbox.ExecuteBatchV1Event\"\x000\x01B*Z(github.com/CodeRushOJ/croj-sandbox/protob\x06proto3"

var (
	file_proto_sandbox_proto_rawDescOnce sync.Once
	file_proto_sandbox_proto_rawDescData []byte
)

func file_proto_sandbox_proto_rawDescGZIP() []byte {
	file_proto_sandbox_proto_rawDescOnce.Do(func() {
		file_proto_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sandbox_proto_rawDesc), len(file_proto_sandbox_proto_rawDesc)))
	})
	return file_proto_sandbox_proto_rawDescData
}

var file_proto_sandbox_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_sandbox_proto_goTypes = []any{
	(ExecuteBatchV1Event_Kind)(0), // 0: sandbox.ExecuteBatchV1Event.Kind
	(*ExecuteRequest)(nil),        // 1: sandbox.ExecuteRequest
	(*ExecuteResponse)(nil),       // 2: sandbox.ExecuteResponse
	(*ExecuteBatchV1Request)(nil), // 3: sandbox.ExecuteBatchV1Request
	(*ExecuteBatchV1Case)(nil),    // 4: sandbox.ExecuteBatchV1Case
	(*ExecuteBatchV1Event)(nil),   // 5: sandbox.ExecuteBatchV1Event
}
var file_proto_sandbox_proto_depIdxs = []int32{
	4, // 0: sandbox.ExecuteBatchV1Request.cases:type_name -> sandbox.ExecuteBatchV1Case
	0, // 1: sandbox.ExecuteBatchV1Event.kind:type_name -> sandbox.ExecuteBatchV1Event.Kind
	2, // 2: sandbox.ExecuteBatchV1Event.result:type_name -> sandbox.ExecuteResponse
	1, // 3: sandbox.SandboxService.Execute:input_type -> sandbox.ExecuteRequest
	3, // 4: sandbox.SandboxService.ExecuteBatchV1:input_type -> sandbox.ExecuteBatchV1Request
	2, // 5: sandbox.SandboxService.Execute:output_type -> sandbox.ExecuteResponse
	5, // 6: sandbox.SandboxService.ExecuteBatchV1:output_type -> sandbox.ExecuteBatchV1Event
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_sandbox_proto_init() }
func file_proto_sandbox_proto_init() {
	if File_proto_sandbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sandbox_proto_rawDesc), len(file_proto_sandbox_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sandbox_proto_goTypes,
		DependencyIndexes: file_proto_sandbox_proto_depIdxs,
		EnumInfos:         file_proto_sandbox_proto_enumTypes,
		MessageInfos:      file_proto_sandbox_proto_msgTypes,
	}.Build()
	File_proto_sandbox_proto = out.File
	file_proto_sandbox_proto_goTypes = nil
	file_proto_sandbox_proto_depIdxs = nil
}
